import { Roboto } from 'next/font/google'
import './globals.css'
import Header from '../components/layout/Header'

const roboto = Roboto({ subsets: ['latin'], weight: ['300', '400', '500'] })

export const metadata = {
  title: 'The Original Buko Pie',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
      <div className="flex flex-col min-h-screen">
      <main className="max-w-4xl mx-auto py-2">
      <Header/>
      {children}</main>
      <footer className="bg-gray-50 py-4">
        <div className="container mx-auto text-center">
          &copy; 2023 All right reserved
        </div>
      </footer>
    </div>
        </body>
    </html>
  )
}
