import { Roboto } from 'next/font/google'
import './globals.css'
import Header from '../components/layout/Header'

const roboto = Roboto({ subsets: ['latin'], weight: ['300', '400', '500'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className='max-w-4xl mx-auto py-2'>
          <Header/>
        {children}  
        <footer className='border-t p-8 text-center'>
            &copy; 2023 All right reserved
          </footer>
        </main>
        </body>
    </html>
  )
}
